apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 3
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: ghcr.io/cabinet-ceipi/cg-ceipi-gestiontransporteur-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: mysql-secret

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password

          resources: 
            requests:
              memory: "256Mi"
              cpu: "250Mi"
            limits: 
              memory: "512Mi"
              cpu: "500"
              
      imagePullSecrets:
        - name: ghcr-secret-auth



---

apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - name: http
      port: 9000
      targetPort: 8000
      nodePort: 32044

